site_name: improvutilities
strict: true

# markdown_extensions:
#   - mkautodoc

nav:
  - Home Docs: index.md
  - Tutorial: tutorial.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md

plugins:
  - autorefs
  - mkdocstrings

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

